In [51]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import MissingIndicator, SimpleImputer

In [52]:
df = pd.read_csv(r'c:\Users\Acer\OneDrive\Desktop\Machine Learning\CSV\tested.csv',usecols=['Age','Fare','Survived'])

In [53]:
df.head()

,Survived,Age,Fare
0,0,34.5,7.8292
1,1,47.0,7.0000
2,0,62.0,9.6875
3,0,27.0,8.6625
4,1,22.0,12.2875


In [54]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [55]:
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [56]:
X_train.head()

,Age,Fare
280,23.0,8.6625
284,2.0,20.2125
40,39.0,13.4167
17,21.0,7.2250
362,31.0,21.0000


In [57]:
si = SimpleImputer()
X_train_trf = si.fit_transform(X_train)
X_test_trf = si.transform(X_test)

In [58]:
X_train_trf

array([[2.30000000e+01, 8.66250000e+00],
       [2.00000000e+00, 2.02125000e+01],
       [3.90000000e+01, 1.34167000e+01],
       [2.10000000e+01, 7.22500000e+00],
       [3.10000000e+01, 2.10000000e+01],
       [8.00000000e+00, 2.60000000e+01],
       [2.93072519e+01, 7.00000000e+00],
       [3.70000000e+01, 8.31583000e+01],
       [1.70000000e+01, 4.71000000e+01],
       [3.10000000e+01, 2.10000000e+01],
       [8.30000000e-01, 9.35000000e+00],
       [2.93072519e+01, 2.65500000e+01],
       [2.20000000e+01, 8.96250000e+00],
       [2.93072519e+01, 2.16792000e+01],
       [2.70000000e+01, 7.89580000e+00],
       [2.10000000e+01, 7.85420000e+00],
       [4.50000000e+01, 6.33583000e+01],
       [2.20000000e+01, 1.05000000e+01],
       [2.93072519e+01, 2.10000000e+01],
       [3.20000000e+01, 7.57920000e+00],
       [2.93072519e+01, 1.45000000e+01],
       [2.50000000e+01, 2.60000000e+01],
       [2.60000000e+01, 2.20250000e+01],
       [2.50000000e+01, 5.54417000e+01],
       [2.930725

In [59]:
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf, y_train)

y_pred = clf.predict(X_test_trf)

accuracy_score(y_test, y_pred)

0.6428571428571429

In [60]:
mi = MissingIndicator()

mi.fit(X_train)

,missing_values,nan
,features,'missing-only'
,sparse,'auto'
,error_on_new,True


In [61]:
mi.features_

array([0, 1])

In [62]:
X_train_missing = mi.transform(X_train)

In [63]:
X_train_missing

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [Fal

In [64]:
X_test_missing = mi.transform(X_test)

In [65]:
X_test_missing

array([[ True, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [Fal

In [66]:

X_train[['Age_NA' , 'Fare_NA']] = X_train_missing

In [67]:
X_train


,Age,Fare,Age_NA,Fare_NA
280,23.0,8.6625,False,False
284,2.0,20.2125,False,False
40,39.0,13.4167,False,False
17,21.0,7.2250,False,False
362,31.0,21.0000,False,False
...,...,...,...,...
299,29.0,7.8542,False,False
22,NaN,31.6833,True,False
72,29.0,7.9250,False,False
15,24.0,27.7208,False,False


In [68]:
X_test[['Age_NA', 'Fare_NA']] = X_test_missing

In [69]:
si = SimpleImputer()
x_train_trf2 = si.fit_transform(X_train)
x_test_trf2 = si.transform(X_test)

In [70]:
clf2 = LogisticRegression()
clf2.fit(x_train_trf2 , y_train)
y_pred2 = clf2.predict(x_test_trf2)
accuracy_score(y_test , y_pred2)

0.6428571428571429

### Using builtin indicator of scikit learn , no need to use above codes

In [71]:
si3 = SimpleImputer(add_indicator=True)
x_train_trf3 = si3.fit_transform(X_train)
x_test_trf3 = si3.transform(X_test)
clf = LogisticRegression()
clf.fit(x_train_trf3 , y_train)
y_pred = clf.predict(x_test_trf3)
accuracy_score(y_test , y_pred )

0.6428571428571429